### ISSUE TITLE
请问项目里自动生成的代码是使用的什么插件，有写过blog讲解项目一些比较生疏的技术点吗？

### ISSUE THREAD

**Issue by suchen2** [wangjianxiandev/WanAndroidFlutter#2]
比如像Locale messages那一块儿的东西

**Comment by wangjianxiandev** [comment]
> 比如像Locale messages那一块儿的东西

https://blog.csdn.net/qq_39424143/article/details/105496999

**Comment by suchen2** [comment]
谢谢了，我想找的就是这一块内容。😊



---原始邮件---
发件人: "wjxbless"<notifications@github.com&gt;
发送时间: 2020年11月4日(周三) 晚上7:39
收件人: "wangjianxiandev/WanAndroidFlutter"<WanAndroidFlutter@noreply.github.com&gt;;
抄送: "彬"<2419248570@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wangjianxiandev/WanAndroidFlutter] 请问项目里自动生成的代码是使用的什么插件，有写过blog讲解项目一些比较生疏的技术点吗？ (#2)




  
比如像Locale messages那一块儿的东西
  
https://blog.csdn.net/qq_39424143/article/details/105496999

**Comment by wangjianxiandev** [comment]
> 谢谢了，我想找的就是这一块内容。😊
> […](#)
> ---原始邮件--- 发件人: "wjxbless"<notifications@github.com&gt; 发送时间: 2020年11月4日(周三) 晚上7:39 收件人: "wangjianxiandev/WanAndroidFlutter"<WanAndroidFlutter@noreply.github.com&gt;; 抄送: "彬"<2419248570@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [wangjianxiandev/WanAndroidFlutter] 请问项目里自动生成的代码是使用的什么插件，有写过blog讲解项目一些比较生疏的技术点吗？ (#2) 比如像Locale messages那一块儿的东西 https://blog.csdn.net/qq_39424143/article/details/105496999 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

一起学习
